# frozen_string_literal: true

require "tmpdir"

# `046`'s C7. `docs/SBOM.md` states what a packaged VSIX ships to a user
# -- every gem vendored into `vendor/bundle` and every production npm
# package -- with versions and licences. It is generated by
# `scripts/generate_sbom.rb` from `core/Gemfile.lock` and
# `vscode/package-lock.json`, and a stale one is not a missing claim but
# a false one.
#
# **What enforced it before this existed: nothing.** The regeneration
# check lived in one step of `make-final-review-bundle.sh`, and nothing
# invoked that script -- not CI, not `release.sh`, not the suite. The
# gate was written down in `RELEASE_CHECKLIST` and run by no one, which
# is the failure `046` is about, arriving in a script instead of a
# document.
RSpec.describe "SBOM" do
  SBOM_SCRIPT = File.expand_path("../../../scripts/generate_sbom.rb", __dir__)
  SBOM_CORE = File.expand_path("../..", __dir__)

  def sbom_check(env = {})
    output = IO.popen(
      { "BUNDLE_GEMFILE" => File.join(SBOM_CORE, "Gemfile") }.merge(env),
      ["ruby", SBOM_SCRIPT, "--check"], err: %i[child out], &:read
    )
    [output, $?.success?]
  end

  it "docs/SBOM.md matches what its generator produces from the lockfiles" do
    output, ok = sbom_check
    expect(ok).to be(true), output
  end

  # Without this, an `--check` that compared a fresh render against
  # itself would pass here for ever and say nothing. The example above
  # cannot distinguish "the SBOM is current" from "the check is inert".
  it "reports a divergence rather than passing on anything" do
    Dir.mktmpdir do |dir|
      path = File.join(dir, "SBOM.md")
      generated = IO.popen(
        { "BUNDLE_GEMFILE" => File.join(SBOM_CORE, "Gemfile"), "SBOM_PATH" => path },
        ["ruby", SBOM_SCRIPT], err: %i[child out], &:read
      )
      expect($?).to be_success, generated

      File.write(path, File.read(path).sub("| MIT |", "| Planted-Not-A-Licence |"))

      output, ok = sbom_check("SBOM_PATH" => path)
      expect(ok).to be(false), "--check passed on a planted divergence:\n#{output}"
      expect(output).to include("Planted-Not-A-Licence")
    end
  end
end
