# frozen_string_literal: true

require "json"

require_relative "rslsp/version"
require_relative "rslsp/logger"
require_relative "rslsp/io/framed_reader"
require_relative "rslsp/io/framed_writer"
require_relative "rslsp/text_document"
require_relative "rslsp/document_store"
require_relative "rslsp/index/symbol_id"
require_relative "rslsp/index/parameter"
require_relative "rslsp/index/declaration"
require_relative "rslsp/index/ancestor_fact"
require_relative "rslsp/index/alias_fact"
require_relative "rslsp/index/reference_candidate"
require_relative "rslsp/index/reference"
require_relative "rslsp/index/file_summary"
require_relative "rslsp/index/source_location"
require_relative "rslsp/index/document_symbol_builder"
require_relative "rslsp/parser_service"
require_relative "rslsp/workspace_index"
require_relative "rslsp/uri_util"
require_relative "rslsp/types"
require_relative "rslsp/semantic/hierarchy_index"
require_relative "rslsp/semantic/method_resolver"
require_relative "rslsp/semantic/method_summary_store"
require_relative "rslsp/semantic/method_analyzer"
require_relative "rslsp/semantic/query_context"
require_relative "rslsp/semantic/query_service"
require_relative "rslsp/semantic/reference_index"
require_relative "rslsp/semantic/reference_resolver"
require_relative "rslsp/diagnostics/finding"
require_relative "rslsp/diagnostics/semantic_context"
require_relative "rslsp/diagnostics/engine"
require_relative "rslsp/rename/plan"
require_relative "rslsp/rename/planner"
require_relative "rslsp/models/model_registry"
require_relative "rslsp/signatures/signature_method"
require_relative "rslsp/signatures/type_converter"
require_relative "rslsp/signatures/overload_resolver"
require_relative "rslsp/signatures/environment"
require_relative "rslsp/signatures/rbi_parser"
require_relative "rslsp/local_inferencer"
require_relative "rslsp/runtime_agent/agent"
require_relative "rslsp/agent_process_manager"
require_relative "rslsp/rails_bootstrap"
require_relative "rslsp/routes/route_registry"
require_relative "rslsp/routes/controller_naming"
require_relative "rslsp/erb/ruby_region_extractor"
require_relative "rslsp/server"

module Rslsp
end
