#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates docs/SBOM.md -- a dependency + license manifest for exactly what
# a packaged VSIX ships to an end user: core/'s own runtime gem dependencies
# (vendored into vscode/core/vendor/bundle by vscode/scripts/copy-core.js,
# per ADR-0004) and vscode/'s own npm production dependency closure --
# vscode-languageclient plus every one of *its* production-flagged
# transitive dependencies (vscode-jsonrpc, semver, a nested minimatch, ...),
# not just the one direct dependency named in package.json.
#
# Deliberately excludes development-only dependencies (rspec, benchmark,
# @vscode/vsce, mocha, typescript, ...) -- those never ship in the VSIX, so
# listing them in a *runtime* SBOM would misrepresent what end users
# actually receive and run. Run manually via `ruby scripts/generate_sbom.rb`
# whenever core/ovallsp.gemspec's, core/Gemfile.lock's, or
# vscode/package-lock.json's production dependency set changes; not run
# automatically by CI/tests (RELEASE_CHECKLIST.md item 8).

require "bundler"
require "json"

ROOT = File.expand_path("..", __dir__)

def gem_rows
  Bundler.with_unbundled_env do
    Dir.chdir(File.join(ROOT, "core")) do
      lockfile = Bundler::LockfileParser.new(Bundler.read_file("Gemfile.lock"))
      runtime_dep_names = Gem::Specification.load(File.join(ROOT, "core", "ovallsp.gemspec"))
                                             .dependencies
                                             .select { |d| d.type == :runtime }
                                             .map(&:name)

      lockfile.specs
              .select { |spec| runtime_dep_names.include?(spec.name) }
              .sort_by(&:name)
              .map do |spec|
        installed = Gem::Specification.find_all_by_name(spec.name, spec.version).first
        license = installed&.license || installed&.licenses&.first || "unknown"
        { name: spec.name, version: spec.version.to_s, license: license, ecosystem: "RubyGems" }
      end
    end
  end
end

def npm_rows
  lock = JSON.parse(File.read(File.join(ROOT, "vscode", "package-lock.json")))

  # `package.json`'s own top-level `dependencies` names only the *direct*
  # production dependency (vscode-languageclient) -- but that package's own
  # production-flagged transitive dependencies (vscode-jsonrpc, semver, a
  # nested minimatch, ...) are exactly as real a part of what a packaged
  # VSIX ships (they land in node_modules/ and get bundled by
  # vscode/scripts/copy-core.js's sibling packaging step, `vsce package`).
  # Found missing by an independent review: reading only `package.json`'s
  # `dependencies` keys produced an SBOM listing 1 npm package when the
  # actual production install closure is 8. `package-lock.json`'s own
  # per-package `dev` flag is already exactly this closure -- npm sets
  # `dev: true` only on a package reachable exclusively through
  # devDependencies, so filtering on its absence needs no separate graph
  # walk.
  lock.fetch("packages", {})
      .select { |key, entry| key.start_with?("node_modules/") && !entry["dev"] }
      .map do |key, entry|
        { name: key.sub(%r{.*node_modules/}, ""), version: entry["version"], license: entry["license"] || "unknown",
          ecosystem: "npm" }
      end
      .sort_by { |row| [row[:name], row[:version]] }
end

def render(rows)
  lines = []
  lines << "# Software Bill of Materials"
  lines << ""
  lines << "Auto-generated by `scripts/generate_sbom.rb` -- do not edit by hand."
  lines << "Regenerate after any change to `core/ovallsp.gemspec`, `core/Gemfile.lock`,"
  lines << "or `vscode/package-lock.json` (any production dependency, direct or"
  lines << "transitive -- not just `package.json`'s own top-level `dependencies`)."
  lines << ""
  lines << "Scope: only what a packaged VSIX actually ships and runs --"
  lines << "core/'s runtime gem dependencies (vendored per ADR-0004) and the full"
  lines << "production install closure of vscode/'s npm dependencies (per"
  lines << "package-lock.json's own `dev` flag, direct and transitive)."
  lines << "Development-only tooling (rspec, @vscode/vsce, typescript, mocha, ...)"
  lines << "is intentionally excluded."
  lines << ""
  lines << "| Ecosystem | Package | Version | License |"
  lines << "|---|---|---|---|"
  rows.each do |row|
    lines << "| #{row[:ecosystem]} | #{row[:name]} | #{row[:version]} | #{row[:license]} |"
  end
  lines << ""
  "#{lines.join("\n")}\n"
end

rows = gem_rows + npm_rows
out_path = File.join(ROOT, "docs", "SBOM.md")
File.write(out_path, render(rows))
puts "wrote #{out_path} (#{rows.size} packages)"
