#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates docs/SBOM.md -- a dependency + license manifest for exactly what
# a packaged VSIX ships to an end user: core/'s own runtime gem dependencies
# (vendored into vscode/core/vendor/bundle by vscode/scripts/copy-core.js,
# per ADR-0004) and vscode/'s own npm *production* dependency.
#
# Deliberately excludes development-only dependencies (rspec, benchmark,
# @vscode/vsce, mocha, typescript, ...) -- those never ship in the VSIX, so
# listing them in a *runtime* SBOM would misrepresent what end users
# actually receive and run. Run manually via `ruby scripts/generate_sbom.rb`
# whenever core/rslsp.gemspec's or vscode/package.json's dependency list
# changes; not run automatically by CI/tests (RELEASE_CHECKLIST.md item 8).

require "bundler"
require "json"

ROOT = File.expand_path("..", __dir__)

def gem_rows
  Bundler.with_unbundled_env do
    Dir.chdir(File.join(ROOT, "core")) do
      lockfile = Bundler::LockfileParser.new(Bundler.read_file("Gemfile.lock"))
      runtime_dep_names = Gem::Specification.load(File.join(ROOT, "core", "rslsp.gemspec"))
                                             .dependencies
                                             .select { |d| d.type == :runtime }
                                             .map(&:name)

      lockfile.specs
              .select { |spec| runtime_dep_names.include?(spec.name) }
              .sort_by(&:name)
              .map do |spec|
        installed = Gem::Specification.find_all_by_name(spec.name, spec.version).first
        license = installed&.license || installed&.licenses&.first || "unknown"
        { name: spec.name, version: spec.version.to_s, license: license, ecosystem: "RubyGems" }
      end
    end
  end
end

def npm_rows
  package_json = JSON.parse(File.read(File.join(ROOT, "vscode", "package.json")))
  lock = JSON.parse(File.read(File.join(ROOT, "vscode", "package-lock.json")))
  prod_deps = package_json.fetch("dependencies", {})

  prod_deps.keys.sort.map do |name|
    entry = lock.dig("packages", "node_modules/#{name}") || {}
    { name: name, version: entry["version"] || prod_deps[name], license: entry["license"] || "unknown", ecosystem: "npm" }
  end
end

def render(rows)
  lines = []
  lines << "# Software Bill of Materials"
  lines << ""
  lines << "Auto-generated by `scripts/generate_sbom.rb` -- do not edit by hand."
  lines << "Regenerate after any change to `core/rslsp.gemspec`, `core/Gemfile.lock`,"
  lines << "or `vscode/package.json`'s `dependencies` (not `devDependencies`)."
  lines << ""
  lines << "Scope: only what a packaged VSIX actually ships and runs --"
  lines << "core/'s runtime gem dependencies (vendored per ADR-0004) and"
  lines << "vscode/'s npm production dependencies. Development-only tooling"
  lines << "(rspec, @vscode/vsce, typescript, mocha, ...) is intentionally excluded."
  lines << ""
  lines << "| Ecosystem | Package | Version | License |"
  lines << "|---|---|---|---|"
  rows.each do |row|
    lines << "| #{row[:ecosystem]} | #{row[:name]} | #{row[:version]} | #{row[:license]} |"
  end
  lines << ""
  "#{lines.join("\n")}\n"
end

rows = gem_rows + npm_rows
out_path = File.join(ROOT, "docs", "SBOM.md")
File.write(out_path, render(rows))
puts "wrote #{out_path} (#{rows.size} packages)"
