# frozen_string_literal: true

require_relative "utf8"

# Generates the index half of `docs/ISSUES.md` from the documents that
# already hold the issues, so the consolidated view cannot drift from
# them.
#
#   ruby scripts/issue_index.rb           # rewrite the generated region
#   ruby scripts/issue_index.rb --check   # exit 1 if it is stale
#
# **It copies nothing that anybody edits.** The register is the store; a
# consolidated document that restated it would be a second place to keep
# right, which is the shape this repository has been bitten by often
# enough to have a rule about it. What this produces is a *derived*
# view -- counts, and one line per open entry pointing at the register --
# regenerated from the same reading the checks make.
#
# The policy half of the document is hand-written and lives above
# `## Index`, exactly as the register's own legend does; `#rebuild` drops
# everything from that heading down and writes it again, so running twice
# changes nothing.
module IssueIndex
  DOC = "docs/ISSUES.md"
  LIVE = "docs/design/tasks/024-deferred-review-findings.md"
  ARCHIVE = "docs/design/tasks/024-deferred-review-findings-resolved.md"
  LIMITS = { "en" => "docs/KNOWN_LIMITATIONS.md", "ja" => "docs/KNOWN_LIMITATIONS.ja.md" }.freeze
  HEADING = "## Index"

  Entry = Struct.new(:number, :title, :status, :kind, :visible, :target, keyword_init: true)

  module_function

  def entries(path)
    return [] unless File.exist?(path)

    File.read(path, encoding: "UTF-8").split(/^## /).drop(1).filter_map do |block|
      number = block[/\A(024\.\w+) /, 1] or next
      Entry.new(
        number: number,
        title: block.lines.first.to_s.strip.sub(/\A#{Regexp.escape(number)} /, ""),
        status: block[/^status: (\S+)/, 1],
        kind: block[/^kind: (\S+)/, 1],
        visible: block[/^user-visible: (\S+)/, 1],
        target: block[/^target: (\S+)/, 1]
      )
    end
  end

  # Which entries each language's KNOWN_LIMITATIONS surfaces to users.
  def documented
    LIMITS.transform_values do |path|
      File.exist?(path) ? File.read(path, encoding: "UTF-8").scan(/<!-- documents: (024\.\w+) -->/).flatten.to_set : Set.new
    end
  end

  def anchor_for(entry)
    slug = "#{entry.number} #{entry.title}".downcase
                                           .gsub(/[^a-z0-9\s-]/, "")
                                           .strip.gsub(/\s+/, "-")
    file = entry.status == "open" ? File.basename(LIVE) : File.basename(ARCHIVE)
    "design/tasks/#{file}##{slug}"
  end

  def render
    open = entries(LIVE).select { |e| e.status == "open" }
    resolved = entries(ARCHIVE)
    surfaced = documented

    out = +"#{HEADING}\n\n"
    out << "*Generated by `scripts/issue_index.rb`. Do not edit below this line;\n"
    out << "edit the register and run the script.*\n\n"
    out << "**#{open.length} open**, #{resolved.length} resolved. "
    out << "#{open.count { |e| e.visible == 'yes' }} of the open ones are user-visible, "
    out << "and #{surfaced['en'].length} are published in `KNOWN_LIMITATIONS` "
    out << "(#{surfaced['ja'].length} in Japanese).\n\n"

    by_target = open.group_by { |e| e.target || "(none)" }
    out << "### Open, by the release they are assigned to\n\n"
    by_target.sort_by { |target, group| [-group.length, target] }.each do |target, group|
      out << "**#{target} — #{group.length}**\n\n"
      out << "| # | kind | user-visible | published | what |\n|---|---|---|---|---|\n"
      group.sort_by { |e| [e.number.length, e.number] }.each do |e|
        published = surfaced["en"].include?(e.number) ? "yes" : "—"
        out << "| [`#{e.number}`](#{anchor_for(e)}) | #{e.kind} | #{e.visible} | #{published} | #{e.title} |\n"
      end
      out << "\n"
    end

    # A user-visible open defect that nothing published is the pairing
    # `deferred_findings_spec` already enforces; counted here so the
    # number is visible rather than only guarded.
    gap = open.select { |e| e.visible == "yes" && !surfaced["en"].include?(e.number) }
    out << "### Open, user-visible, and not published\n\n"
    out << if gap.empty?
             "None. Every open user-visible entry carries a `<!-- documents: -->`\nmarker in both languages.\n"
           else
             gap.map { |e| "- `#{e.number}` #{e.title}\n" }.join
           end
    out
  end

  def rebuild
    source = File.read(DOC, encoding: "UTF-8")
    policy = source.split(/^#{Regexp.escape(HEADING)}$/, 2).first.rstrip
    "#{policy}\n\n#{render}"
  end

  def run(argv)
    unless File.exist?(DOC)
      warn "issue-index: #{DOC} does not exist; create it with a policy section first"
      return 2
    end

    rebuilt = rebuild
    if argv.include?("--check")
      if File.read(DOC, encoding: "UTF-8") == rebuilt
        puts "issue-index: current"
        return 0
      end
      warn "issue-index: #{DOC} is stale. Run `ruby scripts/issue_index.rb`."
      return 1
    end

    File.write(DOC, rebuilt)
    puts "issue-index: rewrote #{DOC}"
    0
  end
end

exit IssueIndex.run(ARGV) if $PROGRAM_NAME == __FILE__
