# frozen_string_literal: true

require_relative "utf8"
require "prism"
require "tmpdir"
require "digest"
require "set"
require "English"
require "rbconfig"

# Measures the `argument-count` check's **recall**: given calls that are
# definitely wrong, how many does it report?
#
# `024.40` asked for G5's precision to be measured on real code rather
# than on gems whose dependencies are absent. Run, the answer was that
# precision has nothing to measure — the check produces **zero** reports
# on 2,095 files of stdlib and gems and on 90 files of this project's own
# `core/lib`. Real Ruby that runs does not call its own methods with the
# wrong number of arguments; the mistakes are made in the editor, seconds
# before they are fixed, and a corpus of committed code cannot hold them.
#
# So the question a corpus *can* answer is the other one. This walks a
# tree for every `def self.name(a, b)` whose parameter list is entirely
# required positionals — the shape where a wrong count is unambiguously
# an error, with no optional, rest, keyword or block parameter to make it
# arguable — writes one too-many and one too-few call for each, and
# reports how many come back.
#
# Usage, from `core/`:
#
#   bundle exec ruby ../scripts/measure_arity_recall.rb lib
#
# The generated probe goes in a `Dir.mktmpdir`, never into the tree being
# measured: `docs/CODE_DISCIPLINE.md`'s rule about fabricated paths and destructive
# code applies to generated files too, and a probe left behind would be
# indexed by the next run as if it were the subject's own code.
module ArityRecall
  Candidate = Struct.new(:owner, :name, :required, :container, keyword_init: true)

  # `def self.x` only. An instance method needs a typed receiver to call
  # it through, which would make the measurement depend on how well
  # inference types the receiver -- a different question, and one that
  # would silently lower this number for a reason that is not G5's.
  class Finder < Prism::Visitor
    attr_reader :found

    def initialize
      @found = []
      @stack = []
      super
    end

    def visit_class_node(node) = push(node, :class) { super }
    def visit_module_node(node) = push(node, :module) { super }

    def visit_def_node(node)
      collect(node) if node.receiver.is_a?(Prism::SelfNode) && !@stack.empty?
      super
    end

    private

    def push(node, kind)
      @stack.push([node.constant_path.slice, kind])
      yield
    ensure
      @stack.pop
    end

    def collect(node)
      parameters = node.parameters
      return unless simple?(parameters)

      @found << Candidate.new(owner: @stack.map(&:first).join("::"), name: node.name,
                              required: parameters ? parameters.requireds.size : 0,
                              container: @stack.last.last)
    end

    def simple?(parameters)
      return true if parameters.nil?

      parameters.optionals.empty? && parameters.rest.nil? && parameters.keywords.empty? &&
        parameters.keyword_rest.nil? && parameters.block.nil? && parameters.posts.empty?
    end
  end

  module_function

  def candidates(roots)
    roots.flat_map { |root| Dir.glob(File.join(root, "**", "*.rb")).sort }.flat_map do |path|
      result = Prism.parse(File.read(path, encoding: "UTF-8"))
      next [] unless result.success?

      finder = Finder.new
      result.value.accept(finder)
      finder.found
    end
  end

  # Returns the probe source and, per generated call, the 1-based line it
  # is on. The line is what the report is matched against, so it is
  # recorded here rather than counted again by the reader.
  def probe(candidates)
    lines = ["# frozen_string_literal: true",
             "# Generated by scripts/measure_arity_recall.rb. Every call below is wrong.",
             "module ArityRecallProbe"]
    expected = []

    candidates.each_with_index do |candidate, index|
      expected << emit(lines, "too_many_#{index}", candidate,
                       Array.new(candidate.required + 1, &:to_s).join(", "))
      next unless candidate.required >= 1

      expected << emit(lines, "too_few_#{index}", candidate,
                       Array.new(candidate.required - 1, &:to_s).join(", "))
    end

    lines << "end"
    [lines.join("\n") + "\n", expected]
  end

  def emit(lines, method_name, candidate, arguments)
    lines << "  def self.#{method_name}"
    lines << "    ::#{candidate.owner}.#{candidate.name}(#{arguments})"
    lines << "  end"
    { line: lines.size - 1, owner: candidate.owner, name: candidate.name,
      required: candidate.required, container: candidate.container,
      kind: method_name.split("_")[0..1].join("_") }
  end
end

if $PROGRAM_NAME == __FILE__
  roots = ARGV.reject { |a| a.start_with?("--") }
  if roots.empty?
    warn "usage: bundle exec ruby ../scripts/measure_arity_recall.rb <dir>... (from core/)"
    exit 1
  end

  missing = roots.reject { |r| Dir.exist?(r) }
  unless missing.empty?
    warn "measure-arity-recall: #{missing.join(" ")} does not exist."
    warn "measure-arity-recall: refusing to run rather than measuring the paths that do."
    exit 1
  end

  found = ArityRecall.candidates(roots)
  if found.empty?
    warn "measure-arity-recall: no `def self.name(a, b)` with an all-required parameter list " \
         "in #{roots.join(" ")}."
    warn "measure-arity-recall: there is nothing to measure here -- say that, rather than " \
         "reporting a recall of 0."
    exit 1
  end

  source, expected = ArityRecall.probe(found)

  Dir.mktmpdir("arity-recall-") do |dir|
    File.write(File.join(dir, "arity_recall_probe.rb"), source)

    driver = File.expand_path("corpus_diagnostics.rb", __dir__)
    output = IO.popen([RbConfig.ruby, driver, *roots, dir], &:read)
    unless $CHILD_STATUS.success?
      warn "measure-arity-recall: the corpus driver failed; nothing was measured."
      exit 1
    end

    # The driver prints LSP positions, which are 0-based.
    reported = output.lines.filter_map do |line|
      next unless line.start_with?("argument-count")

      line.split("\t")[1].split(":")[-2].to_i + 1
    end.to_set

    caught, missed = expected.partition { |probe| reported.include?(probe[:line]) }

    warn "measure-arity-recall: #{found.size} method(s), #{expected.size} deliberately wrong call(s)"
    warn "measure-arity-recall: caught #{caught.size} / #{expected.size}"

    %i[class module].each do |container|
      slice = expected.select { |probe| probe[:container] == container }
      next if slice.empty?

      hit = slice.count { |probe| reported.include?(probe[:line]) }
      warn "measure-arity-recall: on a #{container} receiver -- #{hit} / #{slice.size}"
    end

    missed.each do |probe|
      puts "missed\t#{probe[:kind]}\t#{probe[:container]}\t#{probe[:owner]}.#{probe[:name]}" \
           "\t#{probe[:required]} required"
    end
  end
end
